### ISSUE TITLE
Node.js 0.10.x support

### ISSUE THREAD

**Issue by LinusU** [compat-table/node-compat-table#12]
Thanks for an awesome table! Would love it if you can add the latest Node.js 0.10.x release as well, thanks!

**Comment by williamkapke** [comment]
Anything under 0.12 does not have Promise support and the testing process uses them to run the async tests. I'm sure it _is_ possible to rewrite it to remove this dependency- however 0.10 is basically at End-Of-Life status so I don't personally see too much value to it. That said... if someone submits a PR that makes it work- I'm happy to take a look!

**Comment by dougwilson** [comment]
@LinusU I made a quick pass at a PR in #13. At the very least, the pull request contains the results from 0.10.45, so that's probably useful in some way just by itself, if the goal was to determine the answer for one of the tests.

**Comment by LinusU** [comment]
Awesome 🙌 thank you @dougwilson

**Comment by williamkapke** [comment]
#13 is merged so you now have v0.10 👍 

There are a few things off with v0.12 that we will work through. I'm not 100% sure how accurate the v0.10 tests came out- so if you see anything that doesn't look right please open another issue!

**Comment by dougwilson** [comment]
The 0.12 changes should be fixed in #14 :) It should also address 0.10 accuracy.
