### ISSUE TITLE
escaped html in 'functions > no line break between params and <code>=></code>'

### ISSUE THREAD

**Issue by akatopo** [compat-table/node-compat-table#19]
Minor issue, in the [functions](http://node.green/#functions) section, the subcategory 'no line break between params and =>' includes escaped html (screenshot below). A simple solution would be to use unescaped string interpolation in `index.jade`:

``` diff
diff --git a/index.jade b/index.jade
index 212b909..bdf7954 100644
--- a/index.jade
+++ b/index.jade
@@ -50,7 +50,7 @@ body
             each obj3, subsubcategory in obj2
               tr
                 td.feature.subsub
-                  | #{subsubcategory}
+                  | !{subsubcategory}
                   if obj3.code
                     .info
                       | ?
```

![screenshot from 2016-07-26 16-03-38](https://cloud.githubusercontent.com/assets/2387645/17138812/bf67f30a-534a-11e6-855f-5cc0d1509f1f.png)

**Comment by williamkapke** [comment]
Thanks for pointing this out @akatopo. That text comes from the test name- which we really don't want HTML in anyhow. I added a simple regex replace to strip out the HTML.
