### ISSUE TITLE
Promise.all was failing?

### ISSUE THREAD

**Issue by jskrzypek** [compat-table/node-compat-table#20]
I checked last week and saw that the Promise.all test and a few other specs in the Promise section were failing for 0.12 & 4.x, but now they're not. Am I going crazy?

**Comment by williamkapke** [comment]
You're not going crazy. I caught it a few days ago and fixed it! See https://github.com/williamkapke/node-compat-table/commit/c601a6157da270d901b1abc97a3f411439872e38

Cheers
