### ISSUE TITLE
Flags are displayed over header

### ISSUE THREAD

**Issue by ChALkeR** [compat-table/node-compat-table#24]
Probably header needs a greater z-index.

![screenshot_20161025_191832](https://cloud.githubusercontent.com/assets/291301/19694421/e262f000-9ae7-11e6-9e46-8e5a0b2fdbde.png)

Arch Linux, Chromium 53.0.2785.143 (64-bit).

**Comment by williamkapke** [comment]
Hm... The flags are done via css in a `content: "⚐";` property in a `:before` rule. I guess that causes it to be on top :/

I'm not sure what is the correct fix for this- I tried z-index, but it didn't seem to help. Maybe someone that knows will do a PR 👍

**Comment by ChALkeR** [comment]
It's the `position: absolute` fault, and `z-index: 1` on the header fixes it for me.
