### ISSUE TITLE
node 7?

### ISSUE THREAD

**Issue by paulirish** [compat-table/node-compat-table#25]
Node 7 appears to be missing from the table? A few people on HN curious about the diff between 6 and 7. https://news.ycombinator.com/item?id=12789111

**Comment by williamkapke** [comment]
Gah!

Adding major versions is a manual process. See:
https://github.com/williamkapke/node-compat-table/blob/gh-pages/versions.js#L30

Since I've been on a whirlwind EU trip for Node conferences, I forgot about this. 😖 

Give me a min- I'll update it.

**Comment by paulirish** [comment]
you're a pro. Nice work!
