### ISSUE TITLE
is there a way to see what v6.3.0 supports in the node.green table?

### ISSUE THREAD

**Issue by g-patel** [compat-table/node-compat-table#29]
The oldest v6.x I see in there is v6.9.2.

**Comment by williamkapke** [comment]
The raw test results are here:
https://github.com/williamkapke/node-compat-table/tree/gh-pages/results

... but it's obviously not as friendly to view it like that. I can tell you this however: I have never noticed any feature differences between minor versions-- so just look at any of the 6.x versions.

**Comment by g-patel** [comment]
@williamkapke Thanks.
