### ISSUE TITLE
rename the repo to node.green

### ISSUE THREAD

**Issue by stevemao** [compat-table/node-compat-table#3]
Thanks for the great work!
I'd suggest you to rename  the repo "node-compat-table" to "node.green". This avoids confusion and node.green is a way better name!

**Comment by williamkapke** [comment]
So, I created this- and then decided I liked the domain http://node.green for it.

Mostly though, It is very important to me that they get the credit for the true core of the data. I went out of my way to make sure the repo shows as being forked from kangax/compat-table even though I don't share the files there. I'd like to keep the name as-is to pay pay homage to them.

**Comment by stevemao** [comment]
The repo name doesn't have anything to do with credit and it will always say "forked from kangax/compat-table"
