### ISSUE TITLE
fetch()

### ISSUE THREAD

**Issue by puppetmaster3** [compat-table/node-compat-table#34]
Why not list things like fetch()?

Works in browser, but on node 7 I need a polyfill.

**Comment by williamkapke** [comment]
The `fetch` API proposal is a proposal by WHATWG and is targeted for the web. So it isn't something that would go in Node Core-- which focuses on being small and environment independent. If you have more questions, try http://github.com/nodejs/help or you want, you could even open an Enhancement Proposal at https://github.com/nodejs/node-eps
