### ISSUE TITLE
Object spread/rest?

### ISSUE THREAD

**Issue by kachkaev** [compat-table/node-compat-table#37]
Hi William,

I've been wondering if object spread/rest properties could be added to the table and have finally decided to ask. They seem to exist in kangax tests: https://github.com/kangax/compat-table/blob/ec099c271f6ee4137d0cc6c6da7d19c631b647bb/data-esnext.js#L888-L926

The latest status of the proposal can be viewed here: https://github.com/tc39/proposal-object-rest-spread/issues/32

If there is a good reason to not show spread/rest on node.green, at least there’ll be an issue explaining why. Cheers.

**Comment by williamkapke** [comment]
What are you talking about? They're right here!:
http://node.green/#ESNEXT-candidate--stage-3---object-rest-properties

😆  heh only kidding around... I just added them for you. Enjoy.
