### ISSUE TITLE
es7 support

### ISSUE THREAD

**Issue by stevemao** [compat-table/node-compat-table#4]
node supports `Array.prototype.includes()` and it's actually `es2016`. See https://github.com/nodejs/nodejs.org/pull/434

**Comment by williamkapke** [comment]
Yeah, I've been to this chart looking for it a few time just to find out that it is not here... but in Node.

Right now, ESNext support is pretty low- so there would just be a ton of red. Also, there wouldn't be much need to run the tests on the < v5 version. I think only Array.prototype.includes would be the only thing working.

I **AM** very curious how ESNext would look on Node v6! Maybe we'd find many more things..?

Thanks for bringing this up here. I want to leave this open. A page for ESNext should be done at some point. 👍

**Comment by stevemao** [comment]
There are only two things added in es7. `Array.prototype.includes()` is already supported but I'm not sure about Exponentiation Operator (`**`). Well I'm just up for completeness and trying to be future prove (when es8 comes out, we already have the template, etc).

**Comment by SargoDarya** [comment]
I guess Annotations/Decorators is coming somewhere this year.

**Comment by sedenardi** [comment]
Async/await as well (which was included in Kangax's table, but is admittedly only working on Babel and Edge 14 right now).

**Comment by stevemao** [comment]
For those non standard features, I wonder if we could add a non standard tab if the feature is already supported by nodejs.

**Comment by ChALkeR** [comment]
http://www.ecma-international.org/ecma-262/7.0/index.html — it's approved.

**Comment by williamkapke** [comment]
... they're aaaaallll the way at the bottom- but ES2016 & ES2017 are there now!

The dark grey ES version headers have links to them now:
- http://node.green/#ES2015
- http://node.green/#ES2016
- http://node.green/#ES2017

I'm thinking I'll add some in-page navigation to them soon.

As always: I'm open to ideas on how to make it better 🍻
