### ISSUE TITLE
ssl?

### ISSUE THREAD

**Issue by devsnek** [compat-table/node-compat-table#43]
is there any reason the site doesn't have ssl? you should probably have ssl.

**Comment by williamkapke** [comment]
Just that GitHub doesn't offer it for custom domains. 👎 

See long standing thread:
https://github.com/isaacs/github/issues/156

**Comment by devsnek** [comment]
personally i use cloudflare to add ssl, which is free and also offers some nice caching, you should look into it

**Comment by Krinkle** [comment]
@devsnek +1 for HTTPS support, although caching would not help (might even slow things down) given the site is statically generated and hosted on GitHub Pages, which is already backed by GitHub's CDN.

**Comment by devsnek** [comment]
it wouldn't slow things down but it might give outdated information for a few minutes to hours after the site updates, but it isn't a feature you have to use

**Comment by Krinkle** [comment]
@devsnek I mean that on cache-miss, there is added latency from one CDN to the next. Adding a third caching layer, by itself, doesn't make much sense :-)

**Comment by devsnek** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by devsnek** [comment]
node.green is green now 🎉

**Comment by williamkapke** [comment]
WHOA...
.... WHOA

I just read this and found out. What a great surprise to come home to!

<sub>ALSO: I've checked the Enforce HTTPS checkbox in the settings too!</sub>
