### ISSUE TITLE
Error in test?

### ISSUE THREAD

**Issue by tom-drake** [compat-table/node-compat-table#45]
Hi, there seems to be an error in one of the tests. It fails in all versions with 'Unexpected identifier'.

The test is [constructors require new](http://node.green/#ES2015-built-ins-typed-arrays-constructors-require-new). Looks likes there's some words in that test that shouldn't be 'Updated identifier syntax'?

**Comment by williamkapke** [comment]
Good catch. The error is upstream.

I opened an issue:
https://github.com/kangax/compat-table/issues/1222

Thanks!

**Comment by williamkapke** [comment]
The upstream test was fixed & node.green now shows the correct results. 👍

**Comment by tom-drake** [comment]
OK great, I didn't realise at the time it was upstream. Thanks for opening the issue over there.
