### ISSUE TITLE
Promise.prototype.finally is reported unavailable on Node 9.11.1 but it's behind a flag

### ISSUE THREAD

**Issue by coaxial** [compat-table/node-compat-table#47]
Here: http://node.green/#ES2018-features-Promise-prototype-finally

`Promise.prototype.finally` should be marked as `flag` for Node 9.11.1, running this command shows the functionality can be turned on with a harmony flag:

```
$ node --version
v9.11.1

$ node --v8-options | grep "in progress"
  --harmony_array_prototype_values (enable "harmony Array.prototype.values" (in progress))
  --harmony_function_sent (enable "harmony function.sent" (in progress))
  --harmony_do_expressions (enable "harmony do-expressions" (in progress))
  --harmony_class_fields (enable "harmony public fields in class literals" (in progress))
  --harmony_promise_finally (enable "harmony Promise.prototype.finally" (in progress))
  --harmony_number_format_to_parts (enable "Intl.NumberFormat.prototype.formatToParts" (in progress))
  --harmony_plural_rules (enable "Intl.PluralRules" (in progress))
```

**Comment by williamkapke** [comment]
My understanding it that the `--harmony` flag only activates the features that are staged (the next level beyond "in progress"). This definition has changed from time to time- so It's possible it changed on us again. Looking at the website (https://nodejs.org/en/docs/es6/) it seems to be the same.

If anyone can find different info- please let us know!
