### ISSUE TITLE
Request for adding some notes to readme

### ISSUE THREAD

**Issue by g-plane** [compat-table/node-compat-table#48]
First thanks @williamkapke for making this wonderful repo. It's convenient to check Node.js ECMAScript compatibility.

I have created two modules [node-green](https://github.com/g-plane/node-green-cli) and [node-green-cli](https://github.com/g-plane/node-green-cli). The former module provides Node.js API to check compatibility. And the latter module is a CLI tool.

So can we add some note to the [readme page](https://github.com/williamkapke/node-compat-table/blob/gh-pages/README.md) of this repo? I can submit a PR to finish this once you approved.

Thanks.

**Comment by williamkapke** [comment]
Ok- open a PR!

**Comment by williamkapke** [comment]
Hey- the [format for testers.json just changed](https://github.com/williamkapke/node-compat-table/pull/68)- not sure if that will mess with your module(s)? Just a heads up.

**Comment by g-plane** [comment]
Ok, I will track it later.
