### ISSUE TITLE
Headers misaligned with columns when scrolling

### ISSUE THREAD

**Issue by cpcallen** [compat-table/node-compat-table#50]
To reproduce:

- Open https://node.green/ in a narrow-ish window.
- Scroll to the right.  Note headers scroll to match columns.
- Now scroll down.  Headers jump to the right, and are no longer aligned with their corresponding columns.

Screenshot:

![screen shot 2018-05-01 at 11 02 14](https://user-images.githubusercontent.com/5603958/39485899-279fa4ce-4d2f-11e8-94b2-41680afaf67d.png)

**Comment by williamkapke** [comment]
I finally got around to fiddling with this. I'm not 100% sure it's the best route- but I'm trying `position:sticky` 😟 

As always- happy to get PRs with alternatives!
