### ISSUE TITLE
Stage 4 syntax is missing

### ISSUE THREAD

**Issue by mysticatea** [compat-table/node-compat-table#54]
Hi.

Currently, there are two stage 4 syntactic features:

- [JSON superset](https://github.com/tc39/proposal-json-superset)
- [Optional `catch` binding](https://github.com/tc39/proposal-optional-catch-binding)

However, the next of ES2018 seems Stage 3 in the table, and above two syntactic features are missing.

![image](https://user-images.githubusercontent.com/1937871/42755478-50b731de-8933-11e8-981d-d60f8476fe00.png)

**Comment by williamkapke** [comment]
Finally fixed via #58 !
