### ISSUE TITLE
Add String.prototype.matchAll

### ISSUE THREAD

**Issue by mathiasbynens** [compat-table/node-compat-table#63]

**Comment by joepie91** [comment]
This *is* already included in kangax' compat-table. As I understand it, this draws its data from there? If so, how come it hasn't appeared automatically yet?

**Comment by silverwind** [comment]
> how come it hasn't appeared automatically yet?

Probably because this repo is a fork.

**Comment by williamkapke** [comment]
This was under a new 2020 category which wasn't added to the update script. It's added now.
https://node.green/#ES2020

Thanks for pointing this out!
