### ISSUE TITLE
Adding a link to the spec

### ISSUE THREAD

**Issue by MatthiasKunnen** [compat-table/node-compat-table#64]
I really like node.green as it allows me to see which new features I can expect and which polyfills I can remove. I however find myself regularly wishing for a link to the spec/proposal of a certain feature. 

Since the features imported from [kangax/compat-table](https://github.com/kangax/compat-table) contain links to the spec, it should be possible to edit the [extract script](https://github.com/williamkapke/node-compat-table/blob/3d6aba1c76feb9e262379d1f790eb37cee59cf61/test.sh#L20) to include the spec which should allow adding a link to the spec on the website.   
I would keep the anchor but make the anchor only appear on hover. Implementation is up for debate.

That is, if this change is desired of course.

**Comment by MatthiasKunnen** [comment]
@williamkapke, would you accept PRs for this change?

**Comment by williamkapke** [comment]
Sure! Sounds nice :D
