### ISSUE TITLE
Question: Did something change on node.green?

### ISSUE THREAD

**Issue by tandrewnichols** [compat-table/node-compat-table#66]
I just looked at node.green on Friday, and it looked like it always did. Today, only node v13 is showing (see screenshot). Is this an intentional change or is something going wrong?

<img width="1680" alt="Screen Shot 70" src="https://user-images.githubusercontent.com/2755760/60033227-3326d100-9676-11e9-9047-730aaf690d6d.png">

FWIW, I've checked the console, and there are no errors there.

**Comment by williamkapke** [comment]
Thanks, I had gotten a notification that the build failed during the auto update. The upstream data must have changed in a breaking way. Taking a look now.

**Comment by williamkapke** [comment]
After much digging....

1) The call to fetch the v8 versions had failed on the last update. This caused it to have NO versions on node.green.
2) The autoupdate script uses [n](https://npmjs.com/package/n) to switch versions and run the tests. At some point- their newer versions stopped working with nightly builds
3) [chachracore is no longer publishing NON-windows versions](https://nodejs.org/download/chakracore-nightly/index.tab).. (I just disabled testing them)

Node.green is back up now. Thanks for opening the issue!

**Comment by tandrewnichols** [comment]
Thanks for the very fast turn around!
