### ISSUE TITLE
Auto Update cleared testers.json

### ISSUE THREAD

**Issue by iamstolis** [compat-table/node-compat-table#67]
It seems that something went wrong with the latest Auto Update. It [cleared](https://github.com/williamkapke/node-compat-table/commit/19337eab5bf02654e77edeb139c16188ea4d482a#diff-3cc3c370b197b4f1a3c9e0f961907b53) the content of `testers.json`.

**Comment by williamkapke** [comment]
PR https://github.com/kangax/compat-table/pull/1477 added a reference to [`common. templateStringsPermanentCaching`](https://github.com/kangax/compat-table/pull/1477/files#diff-fc195b1441377fc4b55dba6b24930a8eR5533). Anytime upstream adds new refs from common it causes this. Just part of the fun! :P

[It's easy to fix though.](https://github.com/williamkapke/node-compat-table/commit/272182face8912f180b189df16bccbe393c58783) I've manually ran the updater and they're back now.

Thanks for the heads up!

**Comment by iamstolis** [comment]
Thank you for the quick fix!
