### ISSUE TITLE
Stage 3 Optional Chaining and Nullish Coalescing via Harmony in Node 13 and 14

### ISSUE THREAD

**Issue by Whobeu** [compat-table/node-compat-table#71]
The node.green table should show that Stage 3 Optional Chaining and Nullish Coalescing are supported in Node 13 and Node 14 if the Harmony flags, --harmony-optional-chaining and  --harmony-nullish, respectively, are specified. I've tested both versions with a simple script and they work fine.

**Comment by williamkapke** [comment]
I believe this is addressed along with #77 

Thanks!
