### ISSUE TITLE
Array.prototype.values is said to be supported by Node v0.12.18

### ISSUE THREAD

**Issue by parzh** [compat-table/node-compat-table#72]
When reviewing the support of [`Array.prototype.values`][MDN], I've noticed that Node v0.12.18 **[is said](https://node.green/#ES2015-built-in-extensions-Array-prototype-methods-Array-prototype-values)** to support it (see the rightmost column in the screenshot):

![image](https://user-images.githubusercontent.com/24416112/69620021-539ff080-1045-11ea-9193-ad5d3ea4ae9d.png)

Is that correct?

  [MDN]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/values

**Comment by zloirock** [comment]
Yes, it's correct. [In the original `compat-table` you could see the details.](http://kangax.github.io/compat-table/es6/#cr-array-prototype-values-note)

**Comment by parzh** [comment]
Thanks, Denis!
Couldn't find neither v8 nor Node v0.12.18 there though. Would you mind if I ask, which version of v8 does this version of Node use?

**Comment by zloirock** [comment]
[v8 3.28](https://nodejs.org/dist/index.json)

**Comment by parzh** [comment]
Okay, so, here's what I've found.

According to the JSON, Node v0.12.18 uses v8 of version 3.28.71.20. Weirdly enough, I couldn't find the source code on GitHub for this exact version, but there are release tags [`3.28.71.2`][_2] and [`3.28.71.19`][_19].

### [`3.28.71.2`][_2]
I've tried `3.28.71.2` first. For it, I was able to find a couple of tests for `Array.prototype.push` ([try finding files throughout the repo at this point in history](https://github.com/v8/v8/find/f284b29e37d97d7ee9128055862179dcbda7e398)):

![image](https://user-images.githubusercontent.com/24416112/69623776-26a30c00-104c-11ea-988c-f7d218b052bf.png)

&hellip; but no tests for `Array.prototype.values`:

![image](https://user-images.githubusercontent.com/24416112/69624116-be085f00-104c-11ea-9b85-b69db6b7b78a.png)
_<sup>(these two files test `.push` and `.pop` methods)</sup>_

Also, there is a [file](https://github.com/v8/v8/blob/f284b29e37d97d7ee9128055862179dcbda7e398/test/mjsunit/regress/regress-builtinbust-6.js), that mentions a couple of `Array.prototype.*` methods, and there's no `.values` there (I'm not sure how definitive this is though).

### [`3.28.71.19`][_19]
Then I thought that `.19` might actually be a closer hit to `.20`. However, doing the same steps, I got basically the same results, and still couldn't find anything that would mention `Array.prototype.values`.

  [_2]: https://github.com/v8/v8/releases/tag/3.28.71.2
  [_19]: https://github.com/v8/v8/releases/tag/3.28.71.19

**Comment by zloirock** [comment]
@parzh I wrote above
> [In the original `compat-table` you could see the details.](http://kangax.github.io/compat-table/es6/#cr-array-prototype-values-note)

about [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=615873).

**Comment by parzh** [comment]
> about [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=615873)

Makes sense now, thanks 👍
