### ISSUE TITLE
Optional Chaining and Nullish Coalescing Node 14

### ISSUE THREAD

**Issue by Whobeu** [compat-table/node-compat-table#76]
The latest nightlies of Node 14 now incorporate V8 8.1. Optional Chaining and Nullish Coalescing no longer require a harmony flag to work and do not throw an error. The ES2020 section of Node.green needs to be updated to remove the "Error" flag under Node 14.0.0.

**Comment by Conduitry** [comment]
This looks like it's all set now that the auto update script has been fixed (#77).

**Comment by williamkapke** [comment]
Ah yes. Thanks!
