### ISSUE TITLE
index.html not updating with scheduled runs

### ISSUE THREAD

**Issue by loren138** [compat-table/node-compat-table#77]
node.green currently isn't showing Node 14.4.0 (or any released versions of Node 14) only the (old) nightly.

It looks like the schedule runs are not updating `index.html`.  Also, The most recent run genrated an empty `testers.json` file.

I rolled back locally to 28bbb643c11275e3fb9fbe5ef074bc74fac5cbce and was able to successfully build using `node build.js` and got a build that had a column for `14.4.0`.

Could you check on the build process and see if you can get it to update `index.html` here?

Thanks for creating node.green!

**Comment by williamkapke** [comment]
Yup, I got this worked out over the weekend. Thanks for creating the issue-- but sorry it took sooooo long.
