### ISSUE TITLE
results only shown/built for nightlies 

### ISSUE THREAD

**Issue by ledbit** [compat-table/node-compat-table#78]
It seems like this [auto commit](https://github.com/williamkapke/node-compat-table/commit/3839496ccaa01c9cc430a3fce1a11085ba3a46f3#diff-d7e1a3f9bc342887fea55a0c8ba1c4f5) removed all the versions to be tested, leaving only the nightly. Not sure that was intentional

**Comment by williamkapke** [comment]
🤦 No, that definitely wasn't wanted.  I reverted it ( 883a02161171343c02db5139e2ee8f7d6f171629 )

Thanks for the heads up.

I *think* this happens when https://nodejs.org/dist/index.tab is down (doesn't return results).
