### ISSUE TITLE
Add ES2021 features

### ISSUE THREAD

**Issue by aryehb** [compat-table/node-compat-table#79]
The following features are part of ES2021 and are supported in Node v15+. They are already listed in Kangax's table:
* String.prototype.replaceAll
* Promise.any
* WeakReferences
* Logical Assignment
* numeric separators

**Comment by chharvey** [comment]
@aryehb  also AggregateError

**Comment by williamkapke** [comment]
I found the issue. See: https://github.com/williamkapke/node-compat-table/commit/fef7ba207fb39c9e25421f9407dc2dd79c6a6271

I guess when I wrote that code I was thinking 2020 was far enough in the future!

Thanks for reporting this. It should update tonight with its nightly test run. I'll check on it tomorrow to  be sure.

**Comment by williamkapke** [comment]
I'm glad I checked today- I missed the change needed in the PUG template. Updated/rebuilt... node.green now shows 2021 👍
