### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by GustavoRSSilva** [compat-table/node-compat-table#80]
The link on the page are not working:

The anchor `basic functionality` is pointing to _http://www.ecma-international.org/ecma-262/6.0/#sec-functiondeclarationinstantiation_ But the redirect goes to
https://262.ecma-international.org/6.0/#sec-functiondeclarationinstantiation and it is returning a 404.

<img width="483" alt="Screenshot 2021-05-05 at 17 42 29" src="https://user-images.githubusercontent.com/8384988/117177762-4ace5500-adc9-11eb-81af-fe55bc9d9507.png">

**Comment by ljharb** [comment]
This is a problem with ecma's site; I'll report it.

**Comment by ljharb** [comment]
This should now be fixed.

**Comment by GustavoRSSilva** [comment]
Thanks @ljharb . Closing now.
