### ISSUE TITLE
Node.Green will soon stop working...

### ISSUE THREAD

**Issue by williamkapke** [compat-table/node-compat-table#84]
The node.green tests have been (mostly) happily running nightly for over 6 years now. This has been made possible by the generosity of Heroku using one of their free dynos and their free scheduler addon.

I was email last week that their free dynos will stop running on November 28, 2022 unless it is migrated to a paid plan.
(The static website that is generated is hosted on github pages)

There's nothing in particular that requires it to be hosted by Heroku- so maybe it can be updated to run elsewhere. Unfortunately, I will not be able to commit much time (if any) to making that a possibility.

I've been paying for the existing costs out of my own pocket up to this point- but I think this is a good time to find a new custodian of this project/tool/domain (if one can be found). Preferably a non-commercial entity.

Thoughts?

**Comment by ljharb** [comment]
Can’t they run in a GitHub actions cron?

**Comment by williamkapke** [comment]
I would think so. That would be a good alternative as long as it doesn't go over the monthly minutes.

**Comment by piranna** [comment]
State of this? Seems like node.green has not get updates lately...

**Comment by jakebailey** [comment]
I sent #85 which moves this task to GHA; if it sounds good, I plan to send a followup to parallelize this (as all of the different nodes can be run in parallel without interacting with each other).
